# Helm values for bitnami/rabbitmq
# Deploys RabbitMQ with the Consistent Hashing plugin required by the distributed crawler
# helm upgrade --install rabbitmq oci://registry-1.docker.io/cloudpirates/rabbitmq  -f .\k8s\values\rabbitmq-values.yaml  -n crawler                    

auth:
  username: guest
  password: guest
  erlangCookie: "crawler-rabbitmq-secret-cookie"
installPlugins: [rabbitmq_consistent_hash_exchange  ,  rabbitmq_prometheus]
managementPlugin:
  enables: true

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

persistence:
  enabled: true
  size: 8Gi

# metrics:
#   enabled: true
#   serviceMonitor:
#     enabled: true
#     namespace: monitoring
