# helm repo add redis-stack https://redis-stack.github.io/helm-redis-stack/      
# helm repo update
# helm install my-redis redis-stack/redis-stack --values ./k8s/values/redis-values.yaml -n crawler   


image:
  registry: docker.io
  repository: redis/redis-stack-server
  tag: latest 

global:
  security:
    allowInsecureImages: true

# redisConfig: |
#   loadmodule /opt/redis-stack/lib/redisbloom.so
