apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
  namespace: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler-container
        image: chahatsagarmain/scheduler:main 
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: crawler-env
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "4"
            memory: "2Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 
        
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20 

