apiVersion: v1
kind: Service
metadata:
  name: worker-svc
  namespace: crawler
  labels:
    monitor: enabled
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
